name: Build kernel and integrate KSU Next
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Set up the toolchain
        run: |
          sudo apt update
          sudo apt install -y \
            bc bison build-essential curl flex \
            g++-multilib gcc-multilib git gnupg \
            lib32readline-dev lib32z1-dev \
            libelf-dev liblz4-tool libssl-dev \
            lzop zlib1g-dev pahole dwarves cpio zip \
            python3 python-is-python3 tar perl lz4 jq

      - name: Clone source
        run: |
          git clone --depth=1 -b experimental https://github.com/reddxae/kernel_samsung_sm8550-common-ksu.git

          # Only clone the necessary version of the AOSP Clang (significantly saves time and free space)
          curl -L -o clang.tar.gz https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/ebcc6c3bef363bc539ea39f45b6abae1dce6ff1a/clang-r574158.tar.gz
          mkdir clang-toolchain
          tar -xf clang.tar.gz -C clang-toolchain
          rm clang.tar.gz

      - name: Integrate KernelSU Next
        run: |
          cd kernel_samsung_sm8550-common-ksu

          # Integrate the KernelSU Next development branch into the source
          curl -LSs "https://raw.githubusercontent.com/KernelSU-Next/KernelSU-Next/stable/kernel/setup.sh" | bash -s dev

          # Calculate the current version of KernelSU Next by counting the commits
          cd KernelSU-Next
          COMMIT_VALUE=$(git rev-list --count HEAD)
          echo "KSU_VERSION=$((30000 + ${COMMIT_VALUE:-0}))" >> $GITHUB_ENV

      - name: Set up swap space
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 16

      - name: Build the kernel
        run: |
          # Add AOSP Clang to local PATH
          export PATH="$(pwd)/clang-toolchain/bin:$PATH"

          cd kernel_samsung_sm8550-common-ksu

          # Determine the current kernel version
          echo "KERNEL_VERSION=$(make kernelversion | awk '/^[0-9]/ {print $1}')" >> $GITHUB_ENV

          # Get the current date
          echo "DATE=$(date +%Y%m%d)" >> $GITHUB_ENV

          # Generate configuration
          make -j$(nproc --all) O=out ARCH=arm64 CC=clang LD=ld.lld LLVM=1 LLVM_IAS=1 gki_defconfig || exit 1

          # Run build
          make -j$(nproc --all) O=out ARCH=arm64 CC=clang LD=ld.lld LLVM=1 LLVM_IAS=1 || exit 1

      - name: Package image with AnyKernel3
        run: |
          cp kernel_samsung_sm8550-common-ksu/.github/goodies/AnyKernel3.zip .
          unzip AnyKernel3.zip -d AnyKernel3/
          cp kernel_samsung_sm8550-common-ksu/out/arch/arm64/boot/Image.gz AnyKernel3/

      - name: Upload the flashable kernel
        uses: actions/upload-artifact@v4
        with:
          name: common-${{ env.KERNEL_VERSION }}_ksunext-dev-${{ env.KSU_VERSION }}_${{ env.DATE }}
          path: AnyKernel3/
